### ISSUE TITLE
MDB_BAD_VALSIZE on M1 Macs

### ISSUE THREAD

**Issue by rmckayfleming** [antimer/lmdb#14]
Essentially, any time I try to write to an environment I get an MDB_BAD_VALSIZE error saying "Unsupported size of key/DB name/data, or wrong DUPFIXED size". It happens with the first example from the documentation:
```lisp
(with-temporary-env (*env*)
  (let ((db (get-db "test")))
    (with-txn (:write t)
      (put db "k1" #(2 3))
      (print (g3t db "k1")) ; => #(2 3)
      (del db "k1"))))
```

I was pulling my hair out a bit with this since I thought I was doing something wrong. But it looks like it's a problem on M1 Macs. The same code works properly on my Intel MacBook Pro that is otherwise identical (same OS, libraries, etc). This is on the latest SBCL and LMDB.

My guess is that this is some sort of FFI problem? But unfortunately I'm at the limits of my knowledge/debugging chops with Common Lisp at this point. What can I do to help diagnose this?

**Comment by eudoxia0** [comment]
I think I know what this is: https://github.com/antimer/lmdb/blob/f439b707939a52769dc9747838ff4a616fab14a3/src/liblmdb.lisp#L56-L59
For non-AMD64 (which includes M1) it uses a 32-bit `size_t`.

Which is obviously a big problem, but I never ran into this, because I only considered x86 platforms when developing this. I don't know if CFFI has a portable `size_t` type yet.

Might be worth adding a dependency on https://github.com/JolifantoBambla/cffi-size-t

Try rewriting the above code to just:

```lisp
(defctype size-t  :uint64)
```

And see if that works.

**Comment by rmckayfleming** [comment]
Yep that did it! I switched the feature expressions to:
```lisp
#+(or x86-64 arm64)
(defcytpe size-t :uint64)
#-(or x86-64 arm64)
(defctype size-t :uint32)
```

**Comment by eudoxia0** [comment]
Great. I have to update the code to use the `size_t` from the latest CFFI now.
